source = {
    "source__1": "gitignore.txt .gitignore",
    "source__2": "README.md README.md",
    "source__3": "requirements.txt requirements.txt",
    "source/app__5": "__init__.txt __init__.py",
    "source/app/static/css___6": "style.css style.css",
    "source/app/templates___9": "meta.html meta.html",
    "source/app/templates___10": "navbar_default.html navbar_default.html",
    "source/app/templates___11": "navbar_loggedin.html navbar_loggedin.html",
    "source/app/templates___12": "scripts.html scripts.html",
    "source/app/templates___13": "_render_field.html _render_field.html",
    "source/app/mod_main___18": "__init__.txt __init__.py",
    "source/app/mod_main___15": "main_routes.txt main_routes.py",
    "source/app/mod_main___16": "main_forms.txt main_forms.py",
    "source/app/mod_main/static/css___17": "style.css style.css",
    "source/app/mod_main/templates___18": "index.html index.html",
    "source/app/mod_main/templates___19": "login.html login.html",
    "source/app/mod_main/templates___20": "register.html register.html",
    "source/app/mod_main/templates___21": "user.html user.html",
    "source/app/static/css___22": "fontawesome-all.css fontawesome-all.css",
    "source/app/utils___22": "image_handler.txt image_handler.py",
    "source/app/utils___23": "__init__.txt __init__.py",
    "source/app/static/img___17": "dummy.txt dummy.txt",
}


wtf = {
    'text': 'StringField',
    'checkbox': 'BooleanField',
    'datetime': 'DateTimeField',
    'email': 'EmailField',
    'file': 'FileField',
    'hidden': 'HiddenField',
    'image': 'StringField',
    'number': 'IntegerField',
    'password': 'PasswordField',
    'radio': 'RadioField',
    'select': 'SelectField',
    'textarea': 'TextAreaField',
    'url': 'String'
}
